onine_arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  # kinematics_solver: onine_onine_arm_kinematics/IKFastKinematicsPlugin

  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3

  # position_only_ik: True